### ISSUE TITLE
FossilFuel instances missing required association to ThermalGeneratingUnit

### ISSUE THREAD

**Issue by michaeldford** [epri-dev/GMDM-IOP#14]
Both instances are missing a required association.

**Comment by DanielRLowe** [comment]
@tviegut We've had a few of these now where associations required by the underlying UML have slipped through. Perhaps it might be worth opening an issue on CIMTool to automatically bring in these required associations or otherwise mark them differently. Especially since profiles should be more restrictive than the UML, not less.

**Comment by DanielRLowe** [comment]
@AAndersn I have updated the profiles. Once you have confirmed the 9500 node model has been updated, I'll mark this as closed.

**Comment by AAndersn** [comment]
@michaeldford  - Based on the association, are you expecting a separate FossilFuel instance defined for each GeneratingUnit?

I think you did catch a modeling error where we defined one "LNG" fuel type and then used that for all. It does make some sense to have different fuel definitions as they could be buying from different suppliers / pricing tiers.

**Comment by AAndersn** [comment]
Fixed in #18

**Comment by StevenZ315** [comment]
One FossilFuel still missing ThermalGeneratingUnit association urn:uuid:8450a55b-e1b7-43a0-87d8-842a82356e5c
